version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes: 
      - mongo_db:/data/db

  # Node API service
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: productslist_db
    depends_on:
      - mongo_db

volumes: 
  mongo_db: {}